"""Steam Deck & Linux launch script generator."""

from __future__ import annotations
from pathlib import Path
import os


def generate_gamescope_wrapper(
    output_dir: Path,
    executable_name: str,
    steamdeck_optimized: bool = True,
    use_vulkan: bool = True,
) -> Path:
    """Generate an executable bash launcher script with gamescope and Wine/Proton/native flags."""
    wrapper_path = output_dir / f"run_{executable_name}.sh"
    
    flags = []
    if use_vulkan:
        flags.append("-force-vulkan")

    flags_str = " ".join(flags)

    script_content = f"""#!/usr/bin/env bash
# Generated by UAPorter for Linux & Steam Deck
set -e

SCRIPT_DIR="$(cd "$(dirname "${{BASH_SOURCE[0]}}")" && pwd)"
BIN_PATH="$SCRIPT_DIR/{executable_name}"

chmod +x "$BIN_PATH"

# Prefer GameScope if available (Steam Deck environment)
if command -v gamescope >/dev/null 2>&1; then
    echo "[UAPorter] Launching with GameScope..."
    exec gamescope -W 1280 -H 800 -r 60 -f -- "$BIN_PATH" {flags_str} "$@"
else
    echo "[UAPorter] Launching native Linux player..."
    exec "$BIN_PATH" {flags_str} "$@"
fi
"""

    with open(wrapper_path, "w", encoding="utf-8") as f:
        f.write(script_content)

    os.chmod(wrapper_path, 0o755)
    return wrapper_path


def generate_desktop_entry(
    output_dir: Path,
    game_name: str,
    executable_path: Path,
    icon_path: Path | None = None,
) -> Path:
    """Generate a Freedesktop .desktop shortcut file for Steam Deck desktop/gaming mode."""
    desktop_file = output_dir / f"{game_name}.desktop"

    icon_entry = f"Icon={icon_path.resolve()}\n" if icon_path and icon_path.exists() else ""

    content = f"""[Desktop Entry]
Name={game_name}
Comment=Ported with UAPorter
Exec="{executable_path.resolve()}"
{icon_entry}Terminal=false
Type=Application
Categories=Game;
"""

    with open(desktop_file, "w", encoding="utf-8") as f:
        f.write(content)

    os.chmod(desktop_file, 0o755)
    return desktop_file
